#/usr/bin/perl -w

# This script opens the PDB files generated by the TheCube program in order to translate 
# the solutions so they appear nicely when opened all with pymol.
#use Strict
my $Dir = 'clean';
my $destination = "clean_displaced_nicely";
`mkdir ${destination}`;
my $FileName;
my $x,$y,$z;
my @X,@Y,@Z;
my $mx = 0;
my $my = 0;

opendir (DIR,$Dir) || die "Cannot open directory";
while ($FileName = readdir(DIR))
{
	if ($FileName !~ /^res/){next;}
	open(FILE,"$Dir/$FileName") || die "Could not open the given file";
	@X = ();
	@Y = ();
	@Z = ();
	
	while (my $Line = <FILE>)
	{
		if ($Line !~ /^ATOM/){next;}
		chomp $Line;
		$x = substr($Line, 32, 6);
		$y = substr($Line, 40, 6);
		$z = substr($Line, 48, 6);
		
		push(@X,$x);
		push(@Y,$y);
		push(@Z,$z);
	}
	close(FILE);
	
	$j = 0;
	foreach(@X)
	{
		$X[$j] = $_ + $mx;
		$j++;
	}
	$mx = $mx+6;

	$j = 0;
	foreach(@Y)
	{
		$Y[$j] = $_ + $my;
		$j++;
	}
	
	if ($mx > 18)
	{
		$mx = 0;
		$my = $my+6;
	}
	

	

# Export translations to new files
	my $NewFile = "${destination}/${FileName}.displaced.pdb";
	open(WRITING, ">$NewFile") || die "Could not open file for writing...";
	
	$j=0;
	foreach(@X)
	{
		print WRITING 'ATOM'.' 'x(7-length($j+1)),$j+1,'  BOX BOX     1'.' 'x(8-length($X[$j]));
		printf WRITING '%.3f',$X[$j];
		print WRITING ' 'x(4-length($Y[$j]));
		printf WRITING '%.3f   %.3f',$Y[$j],$Z[$j];
		print WRITING "\n";
		$j++;
	}
	for($j=0;$j<63;$j++)
	{
		printf WRITING 'CONECT   %2d   %2d',$j+1,$j+2;
		print WRITING "\n";
	}
	close WRITING;
}
closedir(DIR);
exit;
